steps:
  # Build & Deploy langsung ke Cloud Run (tanpa registry)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ml-bi-pipeline-api
      - --source=.
      - --region=asia-southeast2
      - --platform=managed
      - --allow-unauthenticated
      - --memory=8Gi
      - --cpu=2
      - --timeout=3600s
      - --concurrency=80
      - --min-instances=0
      - --max-instances=10
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,GCS_BUCKET=${_GCS_BUCKET}
      - --port=8080
      - --set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest

substitutions:
  _GCS_BUCKET: 'convoinsight-assets'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: 1200s
